filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              container.labels.collect_logs: "true"
          config:
           - type: docker
             containers.ids:
               - "${data.docker.container.id}"
output.logstash:
  hosts: "logstash:5044"

logging.metrics.enabled: false